name: repositorypatterm
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  sqflite: ^2.2.8+4
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^1.8.0
  json_serializable: ^3.2.2
  http: ^0.12.1

flutter:


  uses-material-design: true

